#ifndef H_CARL_CONFIG
#define H_CARL_CONFIG

#define CARL_FIRMWARE_VERSION "0"
#define NUM_VOICES 4
#define NUM_PATTERNS 4
#define DEFAULT_TEMPO 120

#define NUM_SWITCHTEST 8
#define NUM_POTTEST 4

#define I2C_SDA 21
#define I2C_SCL 22

#define DEFAULT_BAUD 115200

#endif // !H_CARL_CONFIG
